### ISSUE TITLE
Could you add our paper to your repo?

### ISSUE THREAD

**Issue by nihaomiao** [CroitoruAlin/Diffusion-Models-in-Vision-A-Survey#2]
Hi, @CroitoruAlin, 

Thanks a lot for your efforts to collect these papers!! I am wondering whether you can add our CVPR 2023 paper "Conditional Image-to-Video Generation with Latent Flow Diffusion Models" to this repo, which applies the diffusion model to generate optical flow for video generation. The link to our paper is [here](https://arxiv.org/abs/2303.13744). 

Bests,
Haomiao

**Comment by vladhondru25** [comment]
Hello,

I added your paper. Thank you very much!
